# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ad06a8ea987613258add62420885753c07065fc9d1b3eb1ef67184d374d37deac985fd724e8587d02166eac887b29ccdeeec184a8d3a53c6a340b995ec41924

test:
  secret_key_base: 6b1321e1d10f8440ad76b5c44d6a1c1c99dc3a8781f2006859a146369521e150cdf53dc96976dedf2652e106ab502a8d8cd1989312e7e8798da014ec252d907b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
